dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"


urlpatterns = [
    #dshboards
    
    path('admin_dashboard/',views.admin_dashboard, name="admin_dashboard"),
    path('supervisor_dashboard/',views.supervisor_dashboard, name ="supervisor_dashboard"),
    path('account_dashboard/',views.account_dashboard, name ="account_dashboard"),
    path('front_desk_dashboard/',views.frontdesk_dashboard, name ="frontdesk_dashboard"),
    path('pos_user_dashboard/',views.pos_user_dashboard, name ="pos_user_dashboard"),

    #hotel
    path('admin/hotel-setup/create/',views.hotel_setup, name="hotel_setup"),
    path('admin/hotel_setup/',views.admin_hotel_info, name="hotel_info"),
    path('admin/hotel/delete/<int:pk>/', views.admin_delete_hotel, name='hotel_delete'),

    #hwarehouse
    path('admin/warehouse-setup/create/',views.warehouse_setup, name="warehouse_setup"),
    path('admin/warehouse_setup/',views.warehouse_info, name="warehouse_info"),
    path('admin/warehouse/delete/<int:pk>/', views.warehouse_delete, name='warehouse_delete'),
    path('admin/warehouse/update/<int:pk>/', views.admin_update_warehouse, name='admin_update_warehouse'),
    path('admin/warehouse/update-form/<int:pk>/', views.admin_update_warehouse_form, name='admin_update_warehouse_form'),

     
    #admin views
    # amenities
    path('admin/room-amenities/', views.admin_list_room_amenities, name='admin_list_room_amenities'),
    path('admin/room-amenities/create/', views.admin_create_room_amenity, name='admin_create_room_amenity'),
    path('admin/room-amenities/update/<int:pk>/', views.admin_update_room_amenity, name='admin_update_room_amenity'),
    path('admin/room-amenities/delete/<int:pk>/', views.admin_delete_room_amenity, name='admin_delete_room_amenity'),
    path('admin/room-amenities/update-form/<int:pk>/', views.admin_update_amenity_form, name='admin_update_room_amenity_form'),

    #room type
    path('admin/room-type/', views.admin_list_room_type, name='admin_list_room_types'),
    path('admin/room-type/create/', views.admin_create_room_type, name='admin_create_room_type'),
    path('admin/room-type/update/<int:pk>/', views.admin_update_room_type, name='admin_update_room_type'),
    path('admin/room-type/delete/<int:pk>/', views.admin_delete_room_type, name='admin_delete_room_type'),
    path('admin/room-type/update-form/<int:pk>/', views.admin_update_roomtype_form, name='admin_update_roomtype_form'),

   #room
    path('admin/rooms/', views.admin_list_room, name='admin_list_room'),
    path('admin/room/create/', views.admin_create_room, name='admin_create_room'),
    path('admin/room/update/<int:pk>/', views.admin_update_room, name='admin_update_room'),
    path('admin/room/update-form/<int:pk>/', views.admin_update_room_form, name='admin_update_room_form'),
    path('admin/room/delete/<int:pk>/', views.admin_delete_room, name='admin_delete_room'),
    
    
       #coupon
    path('admin/coupons/', views.admin_list_coupon, name='admin_list_coupon'),
    path('admin/couponcreate/', views.admin_create_coupon, name='admin_create_coupon'),
    path('admin/coupon/update/<int:pk>/', views.admin_update_coupon, name='admin_update_coupon'),
    path('admin/coupon/delete/<int:pk>/', views.admin_delete_coupon, name='admin_delete_coupon'),
    path('admin/coupon/update-form/<int:pk>/', views.admin_update_coupon_form, name='admin_update_coupon_form'),

    #Admin users
    path('admin/privilaged_users/list/', views.admin_users_list, name='admin_users_list'),
    path('admin/privilaged_user/create/', views.add_admin_privilaged_user, name='add_admin_privilaged_user'),
    path('admin/privilaged_user/delete/<int:pk>/', views.admin_delete_privilaged_user, name='admin_delete_privilaged_user'),
    path('admin/privilaged_user/update/<int:pk>/', views.privilaged_user_update, name='privilaged_user_update'),
    path('admin/privilaged_user/update-form/<int:pk>/', views.admin_update_privilaged_user_form, name='admin_update_privilaged_user_form'),
   
   
   
   
    path('admin/view/room_status/',views.admin_room_status, name ="admin_room_status"),
    path('admin/view/booking_list/',views.admin_booking_list, name ="admin_booking_list"),


    #frontdesk
    path('front_desk/room_status/',views.frontdesk_room_status, name ="frontdesk_room_status"),
    path('front_desk/booking_list/',views.frontdesk_booking_list, name ="frontdesk_booking_list"),
    path('frontdesk/booking/', views.front_desk_booking, name='book_room'),
    path('frontdesk/reservation/', views.front_desk_reservation, name='reserve_room'),
    path('font_desk/receipt/<str:booking_id>/', views.receipt_view, name='receipt'),
    # path('font_desk/re_receipt/<int:pk>/', views.re_issue_receipt_view, name='re_receipt'),
    path('frontdesk/add_booking_service/<int:pk>/', views.frontdesk_add_room_service, name="frontdesk_add_booking_service"),
    path('frontdesk/frontdesk_add_additional_charge/<int:pk>/', views.frontdesk_add_additional_charge, name="frontdesk_add_additional_charge"),
    path('frontdesk/checkout_list/', views.frontdesk_checkout_list, name='checkout_list'),
    path('frontdesk/checkout/<int:id>/', views.checkout_view, name='checkout'),
    path('frontdesk/apply-coupon/<int:pk>/', views.frontdesk_apply_coupon_to_booking, name='apply_coupon'),
    path('frontdesk/checkout/payment/<int:pk>/', views.frontdesk_checkout_payment_view, name='checkout_payment'),
    path('frontdesk/checkout/extend_booking/<int:pk>/', views.frontdesk_update_checkout_date, name='frontdesk_update_checkout_date'),

    #pos officer
    path('pos/order_list/', views.pos_orders, name='pos_orders'),
    path('pos/received_stock/', views.user_update_received_stock, name='received_stock'),
    path('pos/mark_product_as_received/<int:pk>/', views.mark_product_as_received, name="mark_as_received"),
   
   #supervisor 
    path('supervisor/booking_list/', views.supervisor_view_bookings, name='supervisor-booking_list'),
    path('supervisor/room_status/', views.supervisor_view_roomstatus, name='supervisor_room_status'),
    path('supervisor/check_out_list/', views.supervisor_checkout_list, name='supervisor_checkout_list'),
    path('supervisor/transaction_list/', views.supervisor_transaction_list, name='supervisor_transaction_list'),

    # authroization
    path('authorization/error/', views.unauthorized, name='unauthorized'),
   
   
]

htmx_views=[
path('get-available-rooms/', views.available_rooms_view, name='get-available-rooms'),

]

urlpatterns += htmx_views

hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page
from pwa import views as pwa_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hrm/', include('hrm.urls')),
    path('booking/', include('bookings.urls')),
    path('inventory/', include('inventory.urls')),
    
    #ckeditor 5
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    #pos
    path('pos/', include('pos.urls')),
    
     #accounting
    path('accounting/', include('accounting.urls')),

    #pwa
    path("", include("pwa.urls")),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from . import views


app_name = "hrm"

urlpatterns = [
    path('quick_link/', views.hrm_quick_links, name='quick_links'),
    path('departments/', views.department_list, name='departments'),
    path('departments/create_department/', views.department_create, name='department_create'),
    path('departments/delete_department/<int:pk>/', views.department_delete, name='department_delete'),
    path('departments/update_department/<int:pk>/', views.department_update, name='department_update'),
    path('departments/update-form/<int:pk>/', views.admin_update_department_form, name='admin_update_department_form'),

    path('departments/locations/', views.department_location_list, name='department_locations'),
    path('departments/create_locations', views.department_location_create, name='department_locations_create'),
    path('departments/delete_locations/<int:pk>/', views.department_location_delete, name='department_locations_delete'),
    path('departments/update_locations/<int:pk>/', views.department_location_update, name='department_locations_update'),
    path('departments/location-update-form/<int:pk>/', views.admin_update_department_location_form, name='admin_update_department_location_form'),

    path('departments/employees/', views.employee_list, name='employees'),
    path('departments/create_employee', views.employee_create, name='employee_create'),
    path('departments/delete_employee/<int:pk>/', views.employee_delete, name='employee_delete'),
    path('departments/update_employee/<int:pk>/', views.employee_update, name='employee_update'),
    path('departments/employee-update-form/<int:pk>/', views.admin_update_employee_form, name='admin_update_employee_form'),


    path('departments/schedules/', views.staff_schedule_list, name='staff_schedule'),
    path('department/current_staff_schedule',views.current_schedule_list, name ="current_schedule_list"),
    path('departments/create_schedule/', views.staff_schedule_create, name='schedule_create'),
    path('departments/delete_schedule/<int:pk>/', views.staff_schedule_delete, name='schedule_delete'),
    path('departments/update_schedule/<int:pk>/', views.staff_schedule_update, name='schedule_update'),
    path('departments/schedule-update-form/<int:pk>/', views.admin_update_schedule_form, name='admin_update_schedule_form'),

    path('departments/daily_attendance/', views.admin_worker_attendance, name='daily_attendance'),

    #old
    path('departments/checkout_attendance/<int:pk>/', views.checkout_employee, name='checkout_employee'),
    
    path('check-in/', views.check_in, name='check_in'),
    path('supervisor_checkin_employee/<int:pk>/', views.supervisor_check_in_employee, name='supervisor_check_in_employee'),
    path('check-out/', views.check_out, name='check_out'),
    
    #new
    path('supervisor_checkout_employee/<int:pk>/', views.check_out_employee, name='supervisor_checkout_employee'),
]

inventory/urls.py
from django.urls import path
from . import views
from dashboard.views import  warehouse_stock


app_name ="inventory"

urlpatterns = [
    # Supplier URLs
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/update/', views.supplier_update, name='supplier_update'),
    path('suppliers/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),
    path('suppliers/update-form/<int:pk>/', views.admin_update_supplier_form, name='admin_update_supplier_form'),

    # categor URLs
    path('categories/', views.category_list, name='category_list'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/<int:pk>/update/', views.category_update, name='category_update'),
    path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('category/update-form/<int:pk>/', views.admin_update_category_form, name='admin_update_category_form'),

    # Equipment URLs
    path('equipments/', views.equipment_list, name='equipment_list'),
    path('equipments/create/', views.equipment_create, name='equipment_create'),
    path('equipments/<int:pk>/update/', views.equipment_update, name='equipment_update'),
    path('equipments/<int:pk>/delete/', views.equipment_delete, name='equipment_delete'),
    path('equipment/update-form/<int:pk>/', views.admin_update_equipment_form, name='admin_update_equipment_form'),


    # Consumable Item URLs
    path('consumable-items/', views.consumable_item_list, name='consumable_item_list'),
    path('consumable-items/create/', views.consumable_item_create, name='consumable_item_create'),
    path('consumable-items/<int:pk>/update/', views.consumable_item_update, name='consumable_item_update'),
    path('consumable-items/<int:pk>/delete/', views.consumable_item_delete, name='consumable_item_delete'),
    path('item/update-form/<int:pk>/', views.admin_update_item_form, name='admin_update_item_form'),


    # Amenity Item URLs
    path('amenity-items/', views.amenity_item_list, name='amenity_item_list'),
    path('amenity-items/create/', views.amenity_item_create, name='amenity_item_create'),
    path('amenity-items/<int:pk>/update/', views.amenity_item_update, name='amenity_item_update'),
    path('amenity-items/<int:pk>/delete/', views.amenity_item_delete, name='amenity_item_delete'),
    path('amenity/update-form/<int:pk>/', views.admin_update_amenity_form, name='admin_update_amenity_form'),


    # Equipment Usage Log URLs
    path('usage-logs/', views.equipment_usage_log_list, name='equipment_usage_log_list'),
    path('usage-logs/create/', views.equipment_usage_log_create, name='equipment_usage_log_create'),
    path('usage-logs/<int:pk>/update/', views.equipment_usage_log_update, name='equipment_usage_log_update'),
    path('usage-logs/<int:pk>/delete/', views.equipment_usage_log_delete, name='equipment_usage_log_delete'),

    # Insurance Policy URLs
    path('insurance-policies/', views.insurance_policy_list, name='insurance_policy_list'),
    path('insurance-policies/create/', views.insurance_policy_create, name='insurance_policy_create'),
    path('insurance-policies/<int:pk>/update/', views.insurance_policy_update, name='insurance_policy_update'),
    path('insurance-policies/<int:pk>/delete/', views.insurance_policy_delete, name='insurance_policy_delete'),

    # Equipment Audit Log URLs
    path('audit-logs/', views.equipment_audit_log_list, name='equipment_audit_log_list'),
    path('audit-logs/create/', views.equipment_audit_log_create, name='equipment_audit_log_create'),
    path('audit-logs/<int:pk>/update/', views.equipment_audit_log_update, name='equipment_audit_log_update'),
    path('audit-logs/<int:pk>/delete/', views.equipment_audit_log_delete, name='equipment_audit_log_delete'),

    # Inspection Checklist URLs
    path('checklists/', views.inspection_checklist_list, name='inspection_checklist_list'),
    path('checklists/create/', views.inspection_checklist_create, name='inspection_checklist_create'),
    path('checklists/<int:pk>/update/', views.inspection_checklist_update, name='inspection_checklist_update'),
    path('checklists/<int:pk>/delete/', views.inspection_checklist_delete, name='inspection_checklist_delete'),
    #inventory
    path('move_product/', views.move_product, name='move_product'),
    path('warehouse/stocks/', warehouse_stock, name='warehouse_stock'),
    path('supervisor/reports/', views.supervisor_reports, name='supervisor_report'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/templates/partials/htmx/available-rooms.html
{% for room in rooms %}
    <option value="{{ room.id }}">{{ room }}</option>
{% endfor %}

dashboard/templates/partials/htmx/edit_amenity_partial.html
<form method="post" action="{% url 'inventory:amenity_item_update' amenity.pk %}" enctype="multipart/form-data" hx-post="{% url 'inventory:amenity_item_update' amenity.pk %}" hx-target="#edit-amenity .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_category_partial.html
<form method="post" action="{% url 'inventory:category_update' category.pk %}" enctype="multipart/form-data" hx-post="{% url 'inventory:category_update' category.pk %}" hx-target="#edit-category .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_coupon_partials.html
<form method="post" action="{% url 'dashboard:admin_update_coupon' coupon.pk %}" enctype="multipart/form-data" hx-post="{% url 'dashboard:admin_update_coupon' coupon.pk %}" hx-target="#edit-coupon .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_department_location_partial.html
<form method="post" action="{% url 'hrm:department_locations_update' location.pk %}" enctype="multipart/form-data" hx-post="{% url 'hrm:department_locations_update'  location.pk %}" hx-target="#edit-department-location .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_department_partial.html
<form method="post" action="{% url 'hrm:department_update' department.pk %}" enctype="multipart/form-data" hx-post="{% url 'hrm:department_update' department.pk %}" hx-target="#edit-department .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_equipment_partial.html
<form method="post" action="{% url 'inventory:equipment_update' equipment.pk %}" enctype="multipart/form-data" hx-post="{% url 'inventory:equipment_update' equipment.pk %}" hx-target="#edit-equipment .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_room_amenity_partials.html
<form method="post" action="{% url 'dashboard:admin_update_room_amenity' amenity.pk %}" enctype="multipart/form-data" hx-post="{% url 'dashboard:admin_update_room_amenity' amenity.pk %}" hx-target="#edit-amenity .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_schedule_partial.html
<form method="post" action="{% url 'hrm:schedule_update' schedule.pk %}" enctype="multipart/form-data" hx-post="{% url 'hrm:schedule_update' schedule.pk %}" hx-target="#edit-schedule .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_supplier_partials.html
<form method="post" action="{% url 'inventory:supplier_update' supplier.pk %}" enctype="multipart/form-data" hx-post="{% url 'inventory:supplier_update' supplier.pk %}" hx-target="#edit-supplier .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/edit_warehouse_partial.html
<form method="post" action="{% url 'dashboard:admin_update_warehouse' warehouse.pk %}" enctype="multipart/form-data" hx-post="{% url 'dashboard:admin_update_warehouse' warehouse.pk %}" hx-target="#edit-warehouse .offcanvas-body" hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex">
        <button type="submit" class="btn w-100 ms-1 py-2 btn-primary">Update</button>
    </div>
</form>

dashboard/templates/partials/htmx/fd_add_room_service.html
<!-- Add: Room Service -->
<div
    class="offcanvas offcanvas-end"
    tabindex="-1"
    id="add-room-service"
    aria-labelledby="add-room-service"
>
    <div class="offcanvas-header">
        <h5 class="offcanvas-title">Add Room Service</h5>
        <button
            type="button"
            class="btn-close"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
        ></button>
    </div>
    <div class="offcanvas-body">
        <form action ="{% url 'dashboard:frontdesk_add_booking_service' 0 %}" method ="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mb-3">


                {{ room_service_form.as_p}}

            </div>


            <div class="d-flex">
                <button type="button" class="btn w-100 me-1 py-2 btn-primary">
                    Clear
                </button>
                <button type="submit" class="btn w-100 ms-1 py-2 btn-dark">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>

dashboard/templates/partials/htmx/fd_extend_booking.html
<!-- Add: Room Service -->
<div
    class="offcanvas offcanvas-end"
    tabindex="-1"
    id="extend-booking"
    aria-labelledby="extend-booking"
>
    <div class="offcanvas-header">
        <h5 class="offcanvas-title">Extend Room Booking</h5>
        <button
            type="button"
            class="btn-close"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
        ></button>
    </div>
    <div class="offcanvas-body">
        <form action ="{% url 'dashboard:frontdesk_update_checkout_date' 0 %}" method ="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mb-3">


                {{ form.as_p}}

            </div>


            <div class="d-flex">
                <button type="button" class="btn w-100 me-1 py-2 btn-primary">
                    Clear
                </button>
                <button type="submit" class="btn w-100 ms-1 py-2 btn-dark">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>

dashboard/templates/partials/htmx/payment_report_snippet.html
<div class="row justify-content-center my-5">
    <div class="col-md-10">
        <div class="card">
            <div class="card-body">

                {% if error_message %}
                    <div class="alert alert-warning" role="alert">
                        {{ error_message }}
                    </div>
                {% elif payment_records %}
                    <h2 class="mt-4">Report Results</h2>
                    <table class="table table-bordered mt-2">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Amount</th>
                                <th>Payment Date</th>
                                <th>Status</th>
                                <th>Source</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for payment in payment_records %}
                                <tr>
                                    <td>{{ payment.id }}</td>
                                    <td>{{ payment.amount }}</td>
                                    <td>{{ payment.payment_date }}</td>
                                    <td>{{ payment.get_status_display }}</td>
                                    <td>{{ payment.get_source_display }}</td>
                                    <td>{{ payment.description }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                {% endif %}
            </div>
        </div>
    </div>
</div>