hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page
from pwa import views as pwa_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hrm/', include('hrm.urls')),
    path('booking/', include('bookings.urls')),
    path('inventory/', include('inventory.urls')),
    
    #ckeditor 5
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    #pos
    path('pos/', include('pos.urls')),
    
     #accounting
    path('accounting/', include('accounting.urls')),

    #pwa
    path("", include("pwa.urls")),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from . import views


app_name = "hrm"

urlpatterns = [
    path('quick_link/', views.hrm_quick_links, name='quick_links'),
    path('departments/', views.department_list, name='departments'),
    path('departments/create_department/', views.department_create, name='department_create'),
    path('departments/delete_department/<int:pk>/', views.department_delete, name='department_delete'),
    path('departments/update_department/<int:pk>/', views.department_update, name='department_update'),
    path('departments/update-form/<int:pk>/', views.admin_update_department_form, name='admin_update_department_form'),

    path('departments/locations/', views.department_location_list, name='department_locations'),
    path('departments/create_locations', views.department_location_create, name='department_locations_create'),
    path('departments/delete_locations/<int:pk>/', views.department_location_delete, name='department_locations_delete'),
    path('departments/update_locations/<int:pk>/', views.department_location_update, name='department_locations_update'),
    path('departments/location-update-form/<int:pk>/', views.admin_update_department_location_form, name='admin_update_department_location_form'),

    path('departments/employees/', views.employee_list, name='employees'),
    path('departments/create_employee', views.employee_create, name='employee_create'),
    path('departments/delete_employee/<int:pk>/', views.employee_delete, name='employee_delete'),
    path('departments/update_employee/<int:pk>/', views.employee_update, name='employee_update'),
    path('departments/employee-update-form/<int:pk>/', views.admin_update_employee_form, name='admin_update_employee_form'),


    path('departments/schedules/', views.staff_schedule_list, name='staff_schedule'),
    path('department/current_staff_schedule',views.current_schedule_list, name ="current_schedule_list"),
    path('departments/create_schedule/', views.staff_schedule_create, name='schedule_create'),
    path('departments/delete_schedule/<int:pk>/', views.staff_schedule_delete, name='schedule_delete'),
    path('departments/update_schedule/<int:pk>/', views.staff_schedule_update, name='schedule_update'),
    path('departments/schedule-update-form/<int:pk>/', views.admin_update_schedule_form, name='admin_update_schedule_form'),

    path('departments/daily_attendance/', views.admin_worker_attendance, name='daily_attendance'),

    #old
    path('departments/checkout_attendance/<int:pk>/', views.checkout_employee, name='checkout_employee'),
    
    path('check-in/', views.check_in, name='check_in'),
    path('supervisor_checkin_employee/<int:pk>/', views.supervisor_check_in_employee, name='supervisor_check_in_employee'),
    path('check-out/', views.check_out, name='check_out'),
    
    #new
    path('supervisor_checkout_employee/<int:pk>/', views.check_out_employee, name='supervisor_checkout_employee'),
]

inventory/urls.py
from django.urls import path
from . import views
from dashboard.views import  warehouse_stock


app_name ="inventory"

urlpatterns = [
    # Supplier URLs
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/update/', views.supplier_update, name='supplier_update'),
    path('suppliers/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),
    path('suppliers/update-form/<int:pk>/', views.admin_update_supplier_form, name='admin_update_supplier_form'),

    # categor URLs
    path('categories/', views.category_list, name='category_list'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/<int:pk>/update/', views.category_update, name='category_update'),
    path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('category/update-form/<int:pk>/', views.admin_update_category_form, name='admin_update_category_form'),

    # Equipment URLs
    path('equipments/', views.equipment_list, name='equipment_list'),
    path('equipments/create/', views.equipment_create, name='equipment_create'),
    path('equipments/<int:pk>/update/', views.equipment_update, name='equipment_update'),
    path('equipments/<int:pk>/delete/', views.equipment_delete, name='equipment_delete'),
    path('equipment/update-form/<int:pk>/', views.admin_update_equipment_form, name='admin_update_equipment_form'),


    # Consumable Item URLs
    path('consumable-items/', views.consumable_item_list, name='consumable_item_list'),
    path('consumable-items/create/', views.consumable_item_create, name='consumable_item_create'),
    path('consumable-items/<int:pk>/update/', views.consumable_item_update, name='consumable_item_update'),
    path('consumable-items/<int:pk>/delete/', views.consumable_item_delete, name='consumable_item_delete'),
    path('item/update-form/<int:pk>/', views.admin_update_item_form, name='admin_update_item_form'),


    # Amenity Item URLs
    path('amenity-items/', views.amenity_item_list, name='amenity_item_list'),
    path('amenity-items/create/', views.amenity_item_create, name='amenity_item_create'),
    path('amenity-items/<int:pk>/update/', views.amenity_item_update, name='amenity_item_update'),
    path('amenity-items/<int:pk>/delete/', views.amenity_item_delete, name='amenity_item_delete'),
    path('amenity/update-form/<int:pk>/', views.admin_update_amenity_form, name='admin_update_amenity_form'),


    # Equipment Usage Log URLs
    path('usage-logs/', views.equipment_usage_log_list, name='equipment_usage_log_list'),
    path('usage-logs/create/', views.equipment_usage_log_create, name='equipment_usage_log_create'),
    path('usage-logs/<int:pk>/update/', views.equipment_usage_log_update, name='equipment_usage_log_update'),
    path('usage-logs/<int:pk>/delete/', views.equipment_usage_log_delete, name='equipment_usage_log_delete'),

    # Insurance Policy URLs
    path('insurance-policies/', views.insurance_policy_list, name='insurance_policy_list'),
    path('insurance-policies/create/', views.insurance_policy_create, name='insurance_policy_create'),
    path('insurance-policies/<int:pk>/update/', views.insurance_policy_update, name='insurance_policy_update'),
    path('insurance-policies/<int:pk>/delete/', views.insurance_policy_delete, name='insurance_policy_delete'),

    # Equipment Audit Log URLs
    path('audit-logs/', views.equipment_audit_log_list, name='equipment_audit_log_list'),
    path('audit-logs/create/', views.equipment_audit_log_create, name='equipment_audit_log_create'),
    path('audit-logs/<int:pk>/update/', views.equipment_audit_log_update, name='equipment_audit_log_update'),
    path('audit-logs/<int:pk>/delete/', views.equipment_audit_log_delete, name='equipment_audit_log_delete'),

    # Inspection Checklist URLs
    path('checklists/', views.inspection_checklist_list, name='inspection_checklist_list'),
    path('checklists/create/', views.inspection_checklist_create, name='inspection_checklist_create'),
    path('checklists/<int:pk>/update/', views.inspection_checklist_update, name='inspection_checklist_update'),
    path('checklists/<int:pk>/delete/', views.inspection_checklist_delete, name='inspection_checklist_delete'),
    #inventory
    path('move_product/', views.move_product, name='move_product'),
    path('warehouse/stocks/', warehouse_stock, name='warehouse_stock'),
    path('supervisor/reports/', views.supervisor_reports, name='supervisor_report'),
]

inventory/templates/pages/amenity_list.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block title %} Admin | Equipments List{% endblock %}

{% block content %}
    <main class="container-fluid px-0">
    {% comment %} sidebar here {% endcomment %}
        {% if request.user.is_admin %}
            {% include '../partials/menubars/admin_sidebar.html' %}

        {% elif request.user.is_supervisor %}
            {% include '../partials/menubars/supervisor_sidebar.html' %}

        {% elif request.user.is_account_officer %}
            {% include '../partials/menubars/accounting_sidebar.html' %}

        {% elif request.user.is_pos_officer %}
            {% include '../partials/menubars/pos_sidebar.html' %}

        {% else %}
            {% include '../partials/menubars/frontdesk_sidebar.html' %}

        {% endif %}

    {% comment %} sidebar ends {% endcomment %}

        <div class="content">


   {% comment %} top header starts {% endcomment %}
            {% include '../partials/top_header.html' %}
   {% comment %} top header ends {% endcomment %}


   {% comment %} body content starts {% endcomment %}

            <div class="px-xl-5 px-lg-4 px-3 py-3  mt-5 page-body">
                {% include '../partials/_messages.html' %}
                <div class="row g-3">
                    <div class="col-sm-12">
                        <div class="d-flex align-items-center justify-content-between flex-wrap">
                            <h3 class="fw-bold mb-0">Amenities</h3>
                            <div class="col-auto d-flex w-sm-100">
                                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#add-equipment">Add New Amenity</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <table class="table dataTable align-middle table-hover table-body" style="width: 100%;">
                                    <thead>
                                        <tr>

                                            <th>Category</th>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>stock quantity </th>
                                            <th>unit price</th>
                                            <th>total_cost</th>
                                            <th>Purchase Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if amenities %}
                                            {% for amenity in amenities %}
                                                <tr>
                                                    <td>{{ amenity.category}}</td>
                                                    <td>{{ amenity.name}}</td>
                                                    <td>{{ amenity.description}}</td>
                                                    <td>{{ amenity.id_code }}</td>
                                                    <td>{{  amenity.cost}}</td>
                                                    <td>{{  amenity.stock_quantity}}</td>
                                                    <td>{{  amenity.supplier}}</td>

                                                    <td>
                                                        <button type="button"
                                                                class="btn"
                                                                hx-get="{% url 'inventory:admin_update_amenity_form' amenity.pk %}"
                                                                hx-target="#edit-amenity .offcanvas-body"
                                                                hx-trigger="click"
                                                                data-bs-toggle="offcanvas"
                                                                data-bs-target="#edit-amenity">
                                                            <i class="fa fa-pencil-square fa-2x"></i>
                                                        </button>
                                                        <a href="#" data-url="{% url 'inventory:amenity_item_delete' 0 %}" onclick="deleteItem(event, {{ amenity.id }})" class="btn"><i class="fa fa-trash text-danger fa-2x"></i></a>

                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% else %}
                                            <div class="text-center">
                                                <h4> No Amenity Added Yet! </h4>

                                            </div>
                                        {% endif %}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- Row End -->

            </div>



{% comment %} modals start {% endcomment %}
<!-- Add Booking-->
            <div
                class="modal fade"
                id="add-equipment"
                tabindex="-1"
                aria-hidden="true"
            >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form action="{% url 'inventory:amenity_item_create' %}" method = "post">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5">Add New Amenity</h1>
                                <button
                                    type="button"
                                    class="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div class="modal-body">


                                {% csrf_token %}
                                <div class="form-group">

                                    {{form.as_p}}
                                </div>



                            </div>
                            <div class="modal-footer">
                                <button
                                    type="button"
                                    class="btn btn-secondary"
                                    data-bs-dismiss="modal"
                                >
                                    Close
                                </button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

<!-- Edit Booking-->
            <div class="offcanvas offcanvas-end" tabindex="-1" id="edit-amenity" aria-labelledby="edit-amenity">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title">Edit Amenity</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
<!-- HTMX will load the form content here -->
                </div>
            </div>

{% comment %} modals end {% endcomment %}


   {% comment %} body content ends {% endcomment %}


        </div>


        <script>
            function deleteItem(event, amenityId) {
                event.preventDefault(); // Prevent the default link behavior

        // Get the URL template from the data attribute and replace the placeholder
                var url = document.querySelector('[data-url]').getAttribute('data-url').replace('0', amenityId);

                Swal.fire({
                    title: 'Are you sure?',
                    text: 'Do you want to delete this Equipment?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                }).then((result) => {
                    if (result.isConfirmed) {
                // Redirect to the URL to perform the delete operation
                        window.location.href = url;
                    }
                });
            }


             // update reload 
            document.addEventListener('htmx:afterRequest', (event) => {
                if (event.detail.xhr && event.detail.xhr.response) {
                    const response = JSON.parse(event.detail.xhr.response);
                    if (response.success) {
                        // Close the offcanvas
                        const offcanvas = document.querySelector('#edit-amenity');
                        if (offcanvas) {
                            const offcanvasInstance = bootstrap.Offcanvas.getInstance(offcanvas);
                            if (offcanvasInstance) {
                                offcanvasInstance.hide();
                            }
                        }
                        // Reload the page
                        location.reload();
                    }
                }
            });
        </script>
    </main>
{% endblock %}

inventory/templates/pages/consumable_item_list.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block title %} Admin | consumable Items List{% endblock %}

{% block content %}
    <main class="container-fluid px-0">
    {% comment %} sidebar here {% endcomment %}
        {% if request.user.is_admin %}
            {% include '../partials/menubars/admin_sidebar.html' %}

        {% elif request.user.is_supervisor %}
            {% include '../partials/menubars/supervisor_sidebar.html' %}

        {% elif request.user.is_account_officer %}
            {% include '../partials/menubars/accounting_sidebar.html' %}

        {% elif request.user.is_pos_officer %}
            {% include '../partials/menubars/pos_sidebar.html' %}

        {% else %}
            {% include '../partials/menubars/frontdesk_sidebar.html' %}

        {% endif %}

    {% comment %} sidebar ends {% endcomment %}

        <div class="content">


   {% comment %} top header starts {% endcomment %}
            {% include '../partials/top_header.html' %}
   {% comment %} top header ends {% endcomment %}


   {% comment %} body content starts {% endcomment %}

            <div class="px-xl-5 px-lg-4 px-3 py-3  mt-5 page-body">
                {% include '../partials/_messages.html' %}
                <div class="row g-3">
                    <div class="col-sm-12">
                        <div class="d-flex align-items-center justify-content-between flex-wrap">
                            <h3 class="fw-bold mb-0">Purchased Items</h3>
                            <div class="col-auto d-flex w-sm-100">
                                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#add-equipment">Add A Purchased Item</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <table class="table dataTable align-middle table-hover table-body" style="width: 100%;">
                                    <thead>
                                        <tr>

                                            <th>Category</th>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>stock quantity </th>
                                            <th>unit price</th>
                                            <th>total_cost</th>
                                            <th>Purchase Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if consumable_items %}
                                            {% for item in consumable_items %}
                                                <tr>
                                                    <td>{{ item.category}}</td>
                                                    <td>{{ item.name}}</td>
                                                    <td>{{ item.description}}</td>
                                                    <td>{{ item.stock_quantity }}</td>
                                                    <td>{{  item.unit_price}}</td>
                                                    <td>{{  item.total_cost}}</td>
                                                    <td>{{  item.purchase_date}}</td>

                                                    <td>
                                                        <button type="button"
                                                                class="btn"
                                                                hx-get="{% url 'inventory:admin_update_item_form' item.pk %}"
                                                                hx-target="#edit-item .offcanvas-body"
                                                                hx-trigger="click"
                                                                data-bs-toggle="offcanvas"
                                                                data-bs-target="#edit-item">
                                                            <i class="fa fa-pencil-square fa-2x"></i>
                                                        </button>
                                                        <a href="#" data-url="{% url 'inventory:consumable_item_delete' 0 %}" onclick="deleteItem(event, {{ item.id }})" class="btn"><i class="fa fa-trash text-danger fa-2x"></i></a>

                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% else %}
                                            <div class="text-center">
                                                <h4> No Item Added Yet! </h4>

                                            </div>
                                        {% endif %}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- Row End -->

            </div>



{% comment %} modals start {% endcomment %}
<!-- Add Booking-->
            <div
                class="modal fade"
                id="add-equipment"
                tabindex="-1"
                aria-hidden="true"
            >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form action="{% url 'inventory:consumable_item_create' %}" method = "post">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5">Add New Equipment</h1>
                                <button
                                    type="button"
                                    class="btn-close"
                                    data-bs-dismiss="modal"
                                    aria-label="Close"
                                ></button>
                            </div>
                            <div class="modal-body">


                                {% csrf_token %}
                                <div class="form-group">

                                    {{form.as_p}}
                                </div>



                            </div>
                            <div class="modal-footer">
                                <button
                                    type="button"
                                    class="btn btn-secondary"
                                    data-bs-dismiss="modal"
                                >
                                    Close
                                </button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

<!-- Edit item-->
            <div class="offcanvas offcanvas-end" tabindex="-1" id="edit-item" aria-labelledby="edit-item">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title">supplier</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
<!-- HTMX will load the form content here -->
                </div>
            </div>


{% comment %} modals end {% endcomment %}


   {% comment %} body content ends {% endcomment %}


        </div>


        <script>
            function deleteItem(event, amenityId) {
                event.preventDefault(); // Prevent the default link behavior

        // Get the URL template from the data attribute and replace the placeholder
                var url = document.querySelector('[data-url]').getAttribute('data-url').replace('0', amenityId);

                Swal.fire({
                    title: 'Are you sure?',
                    text: 'Do you want to delete this Equipment?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                }).then((result) => {
                    if (result.isConfirmed) {
                // Redirect to the URL to perform the delete operation
                        window.location.href = url;
                    }
                });
            }


            // update reload 
            document.addEventListener('htmx:afterRequest', (event) => {
                if (event.detail.xhr && event.detail.xhr.response) {
                    const response = JSON.parse(event.detail.xhr.response);
                    if (response.success) {
                        // Close the offcanvas
                        const offcanvas = document.querySelector('#edit-item');
                        if (offcanvas) {
                            const offcanvasInstance = bootstrap.Offcanvas.getInstance(offcanvas);
                            if (offcanvasInstance) {
                                offcanvasInstance.hide();
                            }
                        }
                        // Reload the page
                        location.reload();
                    }
                }
            });
        </script>
    </main>
{% endblock %}