hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page
from pwa import views as pwa_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hrm/', include('hrm.urls')),
    path('booking/', include('bookings.urls')),
    path('inventory/', include('inventory.urls')),
    
    #ckeditor 5
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    #pos
    path('pos/', include('pos.urls')),
    
     #accounting
    path('accounting/', include('accounting.urls')),

    #pwa
    path("", include("pwa.urls")),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from . import views


app_name = "hrm"

urlpatterns = [
    path('quick_link/', views.hrm_quick_links, name='quick_links'),
    path('departments/', views.department_list, name='departments'),
    path('departments/create_department/', views.department_create, name='department_create'),
    path('departments/delete_department/<int:pk>/', views.department_delete, name='department_delete'),
    path('departments/update_department/<int:pk>/', views.department_update, name='department_update'),
    path('departments/update-form/<int:pk>/', views.admin_update_department_form, name='admin_update_department_form'),

    path('departments/locations/', views.department_location_list, name='department_locations'),
    path('departments/create_locations', views.department_location_create, name='department_locations_create'),
    path('departments/delete_locations/<int:pk>/', views.department_location_delete, name='department_locations_delete'),
    path('departments/update_locations/<int:pk>/', views.department_location_update, name='department_locations_update'),
    path('departments/location-update-form/<int:pk>/', views.admin_update_department_location_form, name='admin_update_department_location_form'),

    path('departments/employees/', views.employee_list, name='employees'),
    path('departments/create_employee', views.employee_create, name='employee_create'),
    path('departments/delete_employee/<int:pk>/', views.employee_delete, name='employee_delete'),
    path('departments/update_employee/<int:pk>/', views.employee_update, name='employee_update'),
    path('departments/employee-update-form/<int:pk>/', views.admin_update_employee_form, name='admin_update_employee_form'),


    path('departments/schedules/', views.staff_schedule_list, name='staff_schedule'),
    path('department/current_staff_schedule',views.current_schedule_list, name ="current_schedule_list"),
    path('departments/create_schedule/', views.staff_schedule_create, name='schedule_create'),
    path('departments/delete_schedule/<int:pk>/', views.staff_schedule_delete, name='schedule_delete'),
    path('departments/update_schedule/<int:pk>/', views.staff_schedule_update, name='schedule_update'),
    path('departments/schedule-update-form/<int:pk>/', views.admin_update_schedule_form, name='admin_update_schedule_form'),

    path('departments/daily_attendance/', views.admin_worker_attendance, name='daily_attendance'),

    #old
    path('departments/checkout_attendance/<int:pk>/', views.checkout_employee, name='checkout_employee'),
    
    path('check-in/', views.check_in, name='check_in'),
    path('supervisor_checkin_employee/<int:pk>/', views.supervisor_check_in_employee, name='supervisor_check_in_employee'),
    path('check-out/', views.check_out, name='check_out'),
    
    #new
    path('supervisor_checkout_employee/<int:pk>/', views.check_out_employee, name='supervisor_checkout_employee'),
]

pos/urls.py
from django.urls import path
from .import views

app_name ="pos"

urlpatterns = [
    
]

htmx_views =[
    path('ordering/',  views.pos_index, name='products'),
    path('products/<slug:slug>/', views.category_products_view, name='category-products'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/increase/<int:item_id>/', views.increase_item_quantity, name='increase_item_quantity'),
    path('cart/decrease/<int:item_id>/', views.decrease_item_quantity, name='decrease_item_quantity'),
    path('cart/update-total/', views.update_cart_total, name='update_cart_total'),
    path('cart/checkout/', views.checkout_view, name='checkout_view'),
    path('cart/process/', views.process_checkout, name='process_checkout'),
    path('cart/receipt/<int:order_id>/', views.print_receipt, name='print_receipt'),
]

urlpatterns += htmx_views

pos/views.py
from .models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from uuid import uuid4
from django.db import transaction
from accounts.models import User  
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from hrm .models import *
from .forms import  updateReceivedItemForm, WaiterCheckoutForm
from django.contrib import messages
from django.urls import reverse
from django.utils.html import escape
from core.decorators import required_roles


@required_roles('is_admin','is_pos_officer','is_supervisor')
def pos_index(request, slug=None):
    if request.user.is_admin or request.user.is_pos_officer or request.user.is_supervisor:
        categories = ProductCategory.objects.all()
        cart = get_user_cart(request)
        total_items = cart.total_items
        
        try: 
            pos_user_location = request.user.employee_profile.department_location
            if slug:
                category = get_object_or_404(ProductCategory, slug=slug)
                products = Product.objects.filter(category=category, department_location=pos_user_location)
            else:
                products = Product.objects.filter(department_location=pos_user_location)

        except:
        # Load all products 
            if slug:
                category = get_object_or_404(ProductCategory, slug=slug)
                products = Product.objects.filter(category=category)
            else:
                products = Product.objects.all() 
    
        context = {
            'categories': categories,
            'products': products,
            'current_slug': slug,
            'cart': cart,
            'total_items': total_items,
        }
        return render(request, 'pages/pos_index.html', context)
    else:
        return redirect('dashboard:unauthorized')


# HTMX view to load products based on category
@required_roles('is_admin','is_pos_officer','is_supervisor')
def category_products_view(request, slug):
    if request.user.is_admin or request.user.is_pos_officer or request.user.is_supervisor:
        category = get_object_or_404(ProductCategory, slug=slug)
        products = Product.objects.filter(category=category)
        return render(request, 'partials/htmx/product_list.html', {'products': products})
    else:
        return redirect('dashboard:unauthorized')

# views.py
@required_roles('is_admin','is_pos_officer','is_supervisor')
def get_user_cart(request):
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
    else:
        if not request.session.session_key:
            request.session.create()
        session_key = request.session.session_key
        cart, _ = Cart.objects.get_or_create(session_key=session_key)
    return cart



@required_roles('is_admin','is_pos_officer','is_supervisor')
def add_to_cart(request, pk):
    if request.user.is_admin or request.user.is_pos_officer or request.user.is_supervisor:
        product = get_object_or_404(Product, pk=pk)
        
        # Check if product is in stock
        if product.stock_quantity <= 0:
            # If out of stock, send a message to the template
            error_message = f'<div style="padding:20px;"><p style="color:red; font-weight:bold; font-size:14px;" class="alert alert-danger alert-dismissible fade show" role="alert">Sorry, the product "{product.name}" is out of stock!</p></div>'
            return HttpResponse(error_message)

        cart = get_user_cart(request)
        
        # Add product to cart
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product, price=product.price)
        if not created:
            cart_item.quantity += 1
            cart_item.save()

        html = render_to_string('partials/htmx/_cart_sidebar.html', {'cart': cart})
        return HttpResponse(html)
    else:
        return redirect('dashboard:unauthorized')



def increase_item_quantity(request, item_id):
    item = get_object_or_404(CartItem, id=item_id)
    item.quantity += 1
    item.save()

    html = render_to_string('partials/htmx/_cart_sidebar.html', {'cart': item.cart})
    return HttpResponse(html)


def decrease_item_quantity(request, item_id):
    item = get_object_or_404(CartItem, id=item_id)
    item.quantity -= 1
    if item.quantity < 1:
        item.delete()
        html = render_to_string('partials/htmx/_cart_sidebar.html', {'cart': item.cart})
        return HttpResponse(html)

    item.save()
    html = render_to_string('partials/htmx/_cart_sidebar.html', {'cart': item.cart})
    return HttpResponse(html)


@required_roles('is_admin','is_pos_officer','is_supervisor')
def checkout_view(request):
    if request.user.is_admin or request.user.is_pos_officer or request.user.is_supervisor:
        cart = get_user_cart(request)
        current_user = request.user
        department_location = None
        waiter_form = None

        # Determine if the user is a customer or privileged user
        if not current_user.is_admin and not current_user.is_supervisor and \
        not current_user.is_account_officer and not current_user.is_frontdesk_officer and \
        not current_user.is_pos_officer and not current_user.is_worker:
            is_customer = True
        else:
            is_customer = False
            # Check if they are employee/users with valid schedules and attendance
            if hasattr(current_user, 'employee_profile'):
                try:
                    pos_user = current_user.employee_profile
                except AttributeError:
                    return HttpResponse('<div style="padding:20px;"><p style="color:red; font-weight:bold; font-size:14px;" class="alert alert-danger alert-dismissible fade show" role="alert"> You have not been given permission to work as a POS Officer </p></div>')

                department_location = current_user.employee_profile.department_location
                now = timezone.now()

                # Check if the employee has a valid schedule for either 'Pos_shift' or 'Waiter_shift'
                pos_schedule = StaffSchedules.objects.filter(
                    employee=pos_user,
                    schedule_type__in=['Pos_shift', 'Waiter_shift'],  # Include both 'Pos_shift' and 'Waiter_shift'
                    schedule_start_date__lte=now.date(),
                    schedule_end_date__gte=now.date(),
                    active=True
                ).first()
            

                if pos_schedule and pos_schedule.start_time <= now.time() <= pos_schedule.end_time:

                    # Check if the POS user has checked in for attendance
                    attendance = Attendance.objects.filter(
                        employee=pos_user,
                        active=True,
                        check_in__date=now.date()
                    ).first()
                
    
                    if attendance:
                        # The POS user has a valid schedule and is checked in, display the waiter form
                        if request.method == 'POST':
                            waiter_form = WaiterCheckoutForm(request.POST, department_location=department_location)
                            if waiter_form.is_valid():
                                waiter = waiter_form.cleaned_data['waiter']
                                # Handle waiter selection for the checkout process
                        else:
                            waiter_form = WaiterCheckoutForm(department_location=department_location)
                else:
                    print('wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww')

        # Render the cart checkout page along with the waiter form (if applicable)
        html = render_to_string('partials/htmx/_cart_checkout.html', {
            'cart': cart,
            'waiter_form': waiter_form if not is_customer else None  # Display the form only if not a customer
        })
        
        return HttpResponse(html)
    else:
        return redirect('dashboard:unauthorized')
   

@required_roles('is_admin','is_pos_officer','is_supervisor')
@transaction.atomic
def process_checkout(request):
    if request.user.is_admin or request.user.is_pos_officer or request.user.is_supervisor:
        if request.method == 'POST':
            # Extract form data
            payment_method = request.POST.get('payment_method')
            cart_id = request.POST.get('cart_id')
            waiter_id = request.POST.get('waiter')
            # waiter = None
            
            # Validate POSUser's schedule and check-in status
            pos_user = request.user.employee_profile
            now = timezone.now()

            # Check if the POS user is within their scheduled shift
            pos_schedule = StaffSchedules.objects.filter(
                employee=pos_user,
                schedule_type='Pos_shift',
                schedule_start_date__lte=now.date(),
                schedule_end_date__gte=now.date(),
                active=True
            ).first()

            if not pos_schedule:
                return JsonResponse({'status': 'error', 'message': 'You are not scheduled for a shift currently.'}, status=403)

            # Check if the current time is within their scheduled shift hours
            if not (pos_schedule.start_time <= now.time() <= pos_schedule.end_time):
                return JsonResponse({'status': 'error', 'message': 'You are not within your scheduled hours.'}, status=403)

            # Check if the POS user has checked in
            attendance = Attendance.objects.filter(
                employee=pos_user,
                active=True,
                check_in__date=now.date()
            ).first()

            if not attendance:

pos/templates/partials/htmx/_cart_checkout.html
{% load static %}
<div class="h-100 d-flex flex-column p-0">
    <div class="pos-sidebar-header">
        <div class="back-btn">
            <button type="button" data-dismiss-class="pos-sidebar-mobile-toggled" data-target="#pos" class="btn border-0">
                <i class="fa fa-chevron-left"></i>
            </button>
        </div>

        <div class="order"> <b>Check-Out</b></div>
    </div>
    <div class="pos-sidebar-nav">
        <ul class="nav nav-tabs nav-fill">
            <li class="nav-item">
                <a class="nav-link active" href="#" data-bs-toggle="tab" data-bs-target="#newOrderTab">ITEMS ({{ cart.items.count }})</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-bs-toggle="tab" data-bs-target="#orderHistoryTab">Order History (0)</a>
            </li>
        </ul>
    </div>


    <form hx-post="{% url 'pos:process_checkout' %}" hx-target="#checkout-result" hx-swap="innerHTML">
        {% csrf_token %}

        <div class="pos-sidebar-body tab-content mb-5" data-scrollbar="true" data-height="100%">
            <div class="tab-pane fade h-100 show active" id="newOrderTab">
                <div class="pos-table">

                    <div class="col-11">
                        <div class="pos-product-thumb">

                            <div class="info d-flex justify-content-between mt-3">
                                <div class="pt-2" > <h6 class="fw-bolder">Total Number of items: </h6></div>
                                <div class=" bg-info px-3 text-light pt-2"><h4>{{ cart.total_items }}</h4></div>
                            </div>
                            <hr>
                            <div class="info d-flex justify-content-between ">
                                <div class="pt-2" > <h6 class="fw-bolder">Total Amount Payable: </h6></div>
                                <div class=" bg-danger px-2 text-light pt-2"><h5>{{ cart.total }}</h5></div>
                            </div>
                            <hr>
                        </div>
                    </div>


                </div>


                <div class="container text-center mb-2 mt-5 ">
                    <h6 class="text-info"> Complete the form below and checkout </h6>
                    <input type="hidden" name="cart_id" value="{{ cart.id }}">
                    <br>
                    <div class="form-group">
                        {{ waiter_form.waiter }}
                    </div>
                    <br>
                    <div class="form-group">

                        <select class="form-control" name="payment_method" id="payment_method" required>
                            <option value="">Select Payment Method</option>
                            <option value="CASH">Cash</option>
                            <option value="CARD">Card</option>
                            <option value="ROOM_CHARGE">Room Charge</option>
                        </select>
                    </div>


                </div>

            </div>

        </div>



        <div class="pos-sidebar-footer">

            <div id="checkout-result"></div>

            <div class="d-flex align-items-center mt-3">

                <button type="submit" class="btn btn-theme rounded-3 text-center flex-1">Checkout</button>
            </div>
        </div>
    </form>
</div>

pos/templates/partials/htmx/_cart_sidebar.html
{% load static %}
<div class="h-100 d-flex flex-column p-0">
    <div class="pos-sidebar-header">
        <div class="back-btn">
            <button type="button" data-dismiss-class="pos-sidebar-mobile-toggled" data-target="#pos" class="btn border-0">
                <i class="fa fa-chevron-left"></i>
            </button>
        </div>

        <div class="order">Order: <b>#0056</b></div>
    </div>
    <div class="pos-sidebar-nav">
        <ul class="nav nav-tabs nav-fill">
            <li class="nav-item">
                <a class="nav-link active" href="#" data-bs-toggle="tab" data-bs-target="#newOrderTab">New Order ({{ cart.items.count }})</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-bs-toggle="tab" data-bs-target="#orderHistoryTab">Order History (0)</a>
            </li>
        </ul>
    </div>
    <div class="pos-sidebar-body tab-content" data-scrollbar="true" data-height="100%">
        <div class="tab-pane fade h-100 show active" id="newOrderTab">
            <div class="pos-table">
                {% for item in cart.items.all %}
                    <div class="row pos-table-row">
                        <div class="col-9">
                            <div class="pos-product-thumb">
                                {% if item.product.image %}
                                <div class="img" style="background-image: url(  {{item.product.image.url}} )"></div>
                                {% else %}
                                <div class="img" style="background-image:url({% static 'frontpage/pos/assets/img/pos/product-1.jpg' %})"></div>
                                {% endif %}
                                <div class="info">
                                    <div class="title">{{ item.product.name }}</div>
                                    <div class="single-price">&#8358 {{ item.product.price }}</div>
                                    <div class="desc">- size: {{ item.product.size }}</div>
                                    <div class="input-group qty">
                                        <div class="input-group-append">
                                            <a href="{% url 'pos:decrease_item_quantity' item.id %}" class="btn btn-default" hx-get="{% url 'pos:decrease_item_quantity' item.id %}" hx-target=".pos-sidebar" hx-swap="innerHTML"><i class="fa fa-minus"></i></a>
                                        </div>
                                        <input type="text" class="form-control" value="{{ item.quantity }}" readonly />
                                        <div class="input-group-prepend">
                                            <a href="{% url 'pos:increase_item_quantity' item.id %}" class="btn btn-default" hx-get="{% url 'pos:increase_item_quantity' item.id %}" hx-target=".pos-sidebar" hx-swap="innerHTML"><i class="fa fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3 total-price">&#8358 {{ item.total_price }}</div>
                    </div>
                {% empty %}
                    <div class="row pos-table-row">
                        <div class="col-12 text-center">Your cart is empty.</div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="tab-pane fade h-100" id="orderHistoryTab">
            <div class="h-100 d-flex align-items-center justify-content-center text-center p-20">
                <div>
                    <div class="mb-3 mt-n5">
                        <svg width="6em" height="6em" viewBox="0 0 16 16" class="text-gray-300" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14 5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5zM1 4v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4H1z" />
                            <path d="M8 1.5A2.5 2.5 0 0 0 5.5 4h-1a3.5 3.5 0 1 1 7 0h-1A2.5 2.5 0 0 0 8 1.5z" />
                        </svg>
                    </div>
                    <h4>No order history found</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="pos-sidebar-footer">
        {% comment %} totals {% endcomment %}

        {% include 'partials/htmx/_cart_total.html' %}
        {% comment %} totals end {% endcomment %}
        <div class="d-flex align-items-center mt-3">

            <a class="btn btn-theme rounded-3 text-center flex-1"
               hx-get="{% url 'pos:checkout_view' %}"
               hx-target=".pos-sidebar"
               hx-swap="innerHTML"
            ><i class="fa fa-shopping-cart d-block fs-18px my-1"></i> Submit Order</a>
        </div>
    </div>
</div>

pos/templates/partials/htmx/_cart_total.html
<div class="d-flex align-items-center mb-2">
    <div>Subtotal</div>
    <div class="flex-1 text-end h6 mb-0">&#8358 {{ cart.subtotal }}</div>
</div>
<div class="d-flex align-items-center">
    {% comment %} <div>Taxes (6%)</div> {% endcomment %}
    {% comment %} <div class="flex-1 text-end h6 mb-0">${{ cart.taxes }}</div> {% endcomment %}
</div>
<hr class="opacity-1 my-10px">
<div class="d-flex align-items-center mb-2">
    <div>Total</div>
    <div class="flex-1 text-end h4 mb-0">&#8358 {{ cart.total }}</div>
</div>

pos/templates/partials/htmx/product_list.html
{% load static %}
{% if products %}
    <div class="product-row">
        {% for product in products %}
            <div class="product-container">
                <a href="#" class="product" data-bs-toggle="modal" data-bs-target="#modalPos"
                   onclick="UpdateModal(event, '{{ product.id }}', '{{ product.name }}', '{{ product.description }}', '{{ product.price }}', '{% if product.image %} {{ product.image.url }} {% endif %}')">
                    {% if product.image %}
                        <div class="img" style="background-image: url( {% if product.image %} {{ product.image.url }} {% endif %})"></div>
                    {% else %}
                        <div class="img" style="background-image: url({% static 'frontpage/pos/assets/img/pos/product-1.jpg' %})"></div>
                    {% endif %}
                    <div class="text">
                        <div class="title">{{ product.name }}&reg;</div>
                        <div class="desc">{{ product.description }}</div>
                        <div class="price">&#8358 {{ product.price }}</div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>No products found.</p>
{% endif %}