core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    
    #frontpages
    path ('', views.index, name="index"),
    path ('about/', views.about_us, name="about"),
    path ('contact_us/', views.contact_us, name="contact"),
    path ('gallery/', views.gallery, name="gallery"),
    path ('gallery_filter/<str:foo>/', views.gallery_filter, name="gallery-filter"),
    path ('room_list/', views.all_rooms, name="all_rooms"),
    path('roomtype/room_list/<slug:slug>/', views.room_list, name='room_type_list'),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    
    path("checkout/<reservation_id>/", views.checkout, name="checkout"),
    path("invoice/<reservation_id>/", views.invoice, name="invoice"),
    
    # path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
        # Payment API
    path('api/checkout-session/<reservation_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<reservation_id>/', views.payment_success, name='success'),
    path('failed/<reservation_id>/', views.payment_failed, name='failed'),
    
]

hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page
from pwa import views as pwa_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hrm/', include('hrm.urls')),
    path('booking/', include('bookings.urls')),
    path('inventory/', include('inventory.urls')),
    
    #ckeditor 5
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    #pos
    path('pos/', include('pos.urls')),
    
     #accounting
    path('accounting/', include('accounting.urls')),

    #pwa
    path("", include("pwa.urls")),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from . import views


app_name = "hrm"

urlpatterns = [
    path('quick_link/', views.hrm_quick_links, name='quick_links'),
    path('departments/', views.department_list, name='departments'),
    path('departments/create_department/', views.department_create, name='department_create'),
    path('departments/delete_department/<int:pk>/', views.department_delete, name='department_delete'),
    path('departments/update_department/<int:pk>/', views.department_update, name='department_update'),
    path('departments/update-form/<int:pk>/', views.admin_update_department_form, name='admin_update_department_form'),

    path('departments/locations/', views.department_location_list, name='department_locations'),
    path('departments/create_locations', views.department_location_create, name='department_locations_create'),
    path('departments/delete_locations/<int:pk>/', views.department_location_delete, name='department_locations_delete'),
    path('departments/update_locations/<int:pk>/', views.department_location_update, name='department_locations_update'),
    path('departments/location-update-form/<int:pk>/', views.admin_update_department_location_form, name='admin_update_department_location_form'),

    path('departments/employees/', views.employee_list, name='employees'),
    path('departments/create_employee', views.employee_create, name='employee_create'),
    path('departments/delete_employee/<int:pk>/', views.employee_delete, name='employee_delete'),
    path('departments/update_employee/<int:pk>/', views.employee_update, name='employee_update'),
    path('departments/employee-update-form/<int:pk>/', views.admin_update_employee_form, name='admin_update_employee_form'),


    path('departments/schedules/', views.staff_schedule_list, name='staff_schedule'),
    path('department/current_staff_schedule',views.current_schedule_list, name ="current_schedule_list"),
    path('departments/create_schedule/', views.staff_schedule_create, name='schedule_create'),
    path('departments/delete_schedule/<int:pk>/', views.staff_schedule_delete, name='schedule_delete'),
    path('departments/update_schedule/<int:pk>/', views.staff_schedule_update, name='schedule_update'),
    path('departments/schedule-update-form/<int:pk>/', views.admin_update_schedule_form, name='admin_update_schedule_form'),

    path('departments/daily_attendance/', views.admin_worker_attendance, name='daily_attendance'),

    #old
    path('departments/checkout_attendance/<int:pk>/', views.checkout_employee, name='checkout_employee'),
    
    path('check-in/', views.check_in, name='check_in'),
    path('supervisor_checkin_employee/<int:pk>/', views.supervisor_check_in_employee, name='supervisor_check_in_employee'),
    path('check-out/', views.check_out, name='check_out'),
    
    #new
    path('supervisor_checkout_employee/<int:pk>/', views.check_out_employee, name='supervisor_checkout_employee'),
]

pos/urls.py
from django.urls import path
from .import views

app_name ="pos"

urlpatterns = [
    
]

htmx_views =[
    path('ordering/',  views.pos_index, name='products'),
    path('products/<slug:slug>/', views.category_products_view, name='category-products'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/increase/<int:item_id>/', views.increase_item_quantity, name='increase_item_quantity'),
    path('cart/decrease/<int:item_id>/', views.decrease_item_quantity, name='decrease_item_quantity'),
    path('cart/update-total/', views.update_cart_total, name='update_cart_total'),
    path('cart/checkout/', views.checkout_view, name='checkout_view'),
    path('cart/process/', views.process_checkout, name='process_checkout'),
    path('cart/receipt/<int:order_id>/', views.print_receipt, name='print_receipt'),
]

urlpatterns += htmx_views

core/models.py
from django.db import models

# Create your models here.

core/views.py
from bookings.models import *
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from bookings.models import Coupon, CouponUsers, Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType, Notification, Bookmark, Review
from datetime import datetime
from decimal import Decimal
import stripe
import json
from django.utils.timezone import now
from .decorators import required_roles  
# from bookings.utils import get_total_selected_items
# Create your views here.


#index view
def index(request):
    template ='pages/index.html'
    
    hotel = Hotel.objects.filter(status='Live').first()
    
    room_types = RoomType.objects.all()

    # total_selected_items = get_total_selected_items(request.session)
    context = {
        'hotel':hotel,
        'room_types':room_types,
        # 'total_selected_items': total_selected_items, 
    }
    
    return render(request, template, context)



#about view
def about_us(request):
    template ='pages/about.html'
    
    return render(request, template)

#contac view
def contact_us(request):
    template ='pages/contact_us.html'
   
    return render(request, template)

#gallery view
def gallery(request):
    template ='pages/gallery.html'
    
    roomtypes = RoomType.objects.all()
    room_gallery = Room.objects.all()
    # total_selected_items = get_total_selected_items(request.session)
    context = {
        "room":roomtypes, 
        "room_gallery":room_gallery,
        # 'total_selected_items': total_selected_items, 
    }
    return render(request, template, context)


def gallery_filter(request, foo):
    template ='pages/gallery.html'
    
    roomtypes = RoomType.objects.all()
    
    foo = foo.replace('-', '')
    rooms = RoomType.objects.get(type=foo)
    room_gallery = Room.objects.filter(room_type=rooms)
    context = {
    "rooms":rooms,
    "room":roomtypes,
    "room_gallery":room_gallery
}

    return render(request, template, context)
    
    

def all_rooms(request):
    
    template ='pages/roomlist.html'
    hotel = Hotel.objects.filter(status='Live').first()
    
    rooms = Room.objects.all()
    # total_selected_items = get_total_selected_items(request.session)
    context = {
    'hotel':hotel,
    'rooms': rooms,
    # 'total_selected_items': total_selected_items, 
     }
    
    return render(request, template, context)



#rooms by category view
def room_list(request,slug):
    
    template ='pages/roomlist.html'
     
    hotel = Hotel.objects.filter(status='Live').first()
   
    room_type = get_object_or_404(RoomType, slug=slug)
    rooms = Room.objects.filter(room_type=room_type)
    
  
    # total_selected_items = get_total_selected_items(request.session)
    context = {
     'hotel':hotel,
     'room_type': room_type,
     'rooms': rooms,
   
    #  'total_selected_items': total_selected_items, 
     }
    
    return render(request, template, context)



# def room_type_detail(request, slug, rt_slug):
#     hotel = get_object_or_404(Hotel, status="Live", slug=slug)
#     room_type = get_object_or_404(RoomType, hotel=hotel, slug=rt_slug)
#     rooms = Room.objects.filter(room_type=room_type, is_available=True)

#     booking_data = request.session.get('booking_data')
#     if not booking_data:
#         messages.warning(request, "Please enter your booking data to check availability.")
#         return redirect("booking:booking_data", hotel.slug)

#     request.session.pop('booking_data', None)

#     room_amenities = [
#         {
#             'room': room,
#             'amenities': RoomInventory.objects.filter(room=room, amenity__isnull=False).select_related('amenity')
#         }
#         for room in rooms
#     ]

#     # Calculate total items in the cart
#     # cart = request.session.get('cart', {})

#     # for room in rooms:
#     #     room.in_cart = str(room.id) in cart

#     # total_selected_items = sum(item['quantity'] for item in cart.values())

#     context = {
#         "hotel": hotel,
#         "room_type": room_type,
#         "rooms": rooms,
#         "room_amenities": room_amenities,
#         "checkin": booking_data['checkin'],
#         "checkout": booking_data['checkout'],
#         "capacity": booking_data['capacity'],
#         "id": booking_data['hotel_id'],
#         # "total_selected_items": total_selected_items,
#     }
#     return render(request, "pages/room_detail.html", context)



def room_type_detail(request, slug, rt_slug):
    hotel = get_object_or_404(Hotel, status="Live", slug=slug)
    room_type = get_object_or_404(RoomType, hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    booking_data = request.session.get('booking_data')
    if not booking_data:
        messages.warning(request, "Please enter your booking data to check availability.")
        return redirect("booking:booking_data", hotel.slug)

    request.session.pop('booking_data', None)

    room_amenities = [
        {
            'room': room,
            'amenities': RoomInventory.objects.filter(room=room, amenity__isnull=False).select_related('amenity')
        }
        for room in rooms
    ]

    context = {
        "hotel": hotel,
        "room_type": room_type,
        "rooms": rooms,
        "room_amenities": room_amenities,
        "checkin": booking_data['checkin'],
        "checkout": booking_data['checkout'],
        "capacity": booking_data['capacity'],
        "id": booking_data['hotel_id'],

    }
    return render(request, "pages/room_detail.html", context)



# def selected_rooms(request):
#     #request.session.pop('selection_data_obj', None)
#     total = 0
#     room_count = 0
#     total_days = 0
#     adult = 0 
#     children = 0 
#     checkin = "0" 
#     checkout = "" 
#     children = 0 
  
    
#     if 'selection_data_obj' in request.session:

#         selection_data = request.session['selection_data_obj']
#         print("jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjSelection Data:", selection_data)  # Print the contents

#         if request.method == "POST":
#             for h_id, item in request.session['selection_data_obj'].items():
                
#                 id = int(item['hotel_id'])
#                 hotel_id = int(item['hotel_id'])

#                 checkin = item["checkin"]
#                 checkout = item["checkout"]
#                 adult = int(item["adult"])
#                 children = int(item["children"])
#                 room_type_ = item["room_type"]
#                 room_id = int(item["room_id"])
                
#                 user = request.user
#                 hotel = Hotel.objects.get(id=id)
#                 room = Room.objects.get(id=room_id)
#                 room_type = RoomType.objects.get(id=room_type_)

                
#             date_format = "%Y-%m-%d"
#             checkin_date = datetime.strptime(checkin, date_format)
#             checout_date = datetime.strptime(checkout, date_format)
#             time_difference = checout_date - checkin_date
#             total_days = time_difference.days

#             # Get and parse full name
#             full_name = request.POST.get("full_name")
#             email = request.POST.get("email")
#             phone = request.POST.get("phone")

#             # Split the full name to first and last names
#             name_parts = full_name.split()
#             first_name = name_parts[0] if name_parts else ""
#             last_name = " ".join(name_parts[1:]) if len(name_parts) > 1 else ""

#             # Create the booking
#             booking = Booking.objects.create(
#                 hotel=hotel,
#                 room_type=room_type,
#                 check_in_date=checkin,
#                 check_out_date=checkout,
#                 num_adults=adult,
#                 num_children=children,
#             )

#             if request.user.is_authenticated:
#                 booking.user = request.user
#                 booking.save()
#             else:
#                 user = User.objects.filter(email=email).first() 
                
#                 if not user:
#                     # If user doesn't exist, create a new one
#                     user = User(email=email, username=email)
#                     user.set_password(phone)  # Set phone number as password
#                     user.first_name = first_name
#                     user.last_name = last_name
#                     user.save()
                    
#                     booking.user = user
#                     booking.save()           

#             for h_id, item in request.session['selection_data_obj'].items():
#                 room_id = int(item["room_id"])
#                 room = Room.objects.get(id=room_id)
                
#                 booking = Booking.objects.create(
#                     hotel=hotel,
#                     room_type=room_type,
#                     room=room,  # Assign a single room per booking
#                     check_in_date=checkin,
#                     check_out_date=checkout,
#                     num_adults=adult,
#                     num_children=children,
#                     user=request.user if request.user.is_authenticated else user
#                 )
                
#                 # Add total amount calculations if needed
#                 days = total_days
#                 print('ccccccccccccccccccccccccccccccccccccccccccccccccc', days)
#                 price = room_type.base_price if not room.price_override else room.price_override

core/templates/partials/_footer.html
{% load static %}


{% comment %} <div class="py-5 bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <div class="newslatter">
                    <h3 class="text-center text-white">Get updates &amp; exclusive offers</h3>
                    <p class="text-center">Sign up to our newsletter to be the first to hear about<br class="d-none d-lg-block">new openings, offers and more.</p>
                    <div class="input-group mb-3">
                        <input type="text" name="youremail" id="youremail" class="form-control border-0 rounded-0" placeholder="Enter email here..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary rounded-0 border-0" type="button" id="_button-addon2" onClick="subscribeemail()">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> {% endcomment %}

<footer class="main-footer py-5 border-top-muted bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-xl-3 mb-5">
                <div class="footer-about">
                    <div class="footer-logo mb-3">
                        <a href="index.html"><img src="assets/img/2021-11-18/F.png" alt class="img-fluid"></a>
                    </div>
                    Plot-7, Road-02, Hotel Motel Zone, San Francisco Road, United States of America <div><br></div>
                    {% comment %} <a href="https://hotel.bdtask-demo.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="751c1b131a351110181a5b161a18">[email&#160;protected]</a> {% endcomment %}
                </div>
            </div>
            <div class="col-lg-7 col-xl-7 offset-xl-1">
                <div class="row">
                    <div class="col-sm-6 col-md-4 col-lg-4 mb-3 mb-lg-0">
                        <h3 class="link-title fs-18 mb-3 font-weight-600 position-relative text-white">
                            Pages</h3>
                        <ul class="footer-link list-unstyled menu mb-0">
                            <li class="mb-2"><a class="link d-block font-weight-500" href="{% url "core:index" %}">Home</a></li>
                            <li class="mb-2"><a class="link d-block font-weight-500" href="{% url "core:about" %}">About Us</a></li>
                            <li class="mb-2"><a class="link d-block font-weight-500" href="{% url "core:contact" %}">Contact Us</a></li>
                            <li class="mb-2"><a class="link d-block font-weight-500" href="{% url "core:gallery" %}">Gallery</a></li>
                            <li class="mb-2"><a class="link d-block font-weight-500" href="index.html">My Profile</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4 mb-3 mb-lg-0">
                        <h3 class="link-title fs-18 mb-3 font-weight-600 position-relative text-white">
                            Social Link</h3>
                        <ul class="list-unstyled social-icon">
                            <li><a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer"> <i class="fab fa-instagram icon-wrap"></i> <span>Instagram </span> </a></li>
                            <li><a href="https://twitter.com/" target="_blank" rel="noopener noreferrer"> <i class="fab fa-twitter icon-wrap"></i> <span>Twitter</span> </a></li>
                            <li><a href="https://dribbble.com/" target="_blank" rel="noopener noreferrer"> <i class="fab fa-dribbble icon-wrap"></i> <span>Dribbble</span> </a></li>
                            <li><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer"> <i class="fab fa-facebook-f icon-wrap"></i> <span>Facebook</span> </a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <h3 class="link-title fs-18 mb-3 font-weight-600 position-relative text-white">
                            Company Policy</h3>
                        <ul class="footer-link list-unstyled menu mb-0">
                            <li class="mb-2"><a class="link d-block font-weight-500" href="privacy.html">Privacy</a></li>
                            <li class="mb-2"><a class="link d-block font-weight-500" href="terms.html">Terms & Conditions</a></li>
                        </ul> </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="sub-footer border-top-muted bg-dark py-3">
    <div class="container">
        <div class="row justify-content-end align-items-center">
            <div class="col-md-6">
                <div class="copy">Powered by Arcadia</div>
            </div>
            <div class="col-md-6">
                <ul class="list-unstyled text-right mb-0">
                    <li class="list-inline-item"><a href="privacy.html" class="text-white">Privacy</a></li>
                    <li class="list-inline-item"><a href="terms.html" class="text-white">Terms &amp; Conditions</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

core/templates/partials/_nav.html
{% load static %}
<!-- ================================navbar======================================= -->
<!-- use this as the navbar.html -->
<nav class="navbar navbar-expand-lg navbar-light header-sticky shadow-sm bg-dark">
    <a class="navbar-brand" href="{% url 'core:index' %}"><img src="{% static 'frontpage/assets/img/boutiquehotel.png' %}" alt width="80px"></a>
    <div class="d-flex order-lg-last">
        <ul class="navbar-right d-flex align-items-center list-unstyled mb-0">

            <li class="nav-item login">
                <a class="nav-link" href="{% url 'signin' %}"><i class="far fa-user-circle d-lg-none"></i><span class="d-none d-lg-block text-light">Sign In</span></a>
            </li>

           

            {% comment %} <li class="nav-item mx-4">
                <li class="nav-item mx-4">
                    <a href="" class="btn btn-success px-4 border text-light">
                        <i class="fas fa-bed"></i>
                        {% include 'partials/htmx/cart_count.html' %}
                    </a>
                </li>
            </li>               {% endcomment %}

            <li class="nav-item mx-4">
                <a href="" class="btn btn-success px-4 border text-light">
                    <i class="fas fa-bed"></i>
                    {% include 'partials/htmx/cart_count.html' %}
                </a>
            </li>
            



            <li class="nav-item nav-btn">

                <div class="">
                    <a href="{% url 'core:all_rooms' %}">
                        <button  class="border-0 d-none d-lg-inline-block nav-link" style="background-color: #fee277; color:#000; font-weight:600;">
                            <i class="far fa-calendar-alt mr-2 text-light"></i><span>Book Now</span>
                        </button>
                    </a>
                </div>

            </li>
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item  active">
                <a class="nav-link text-light " href="{% url 'core:index' %}">Home</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li>
            <li class="nav-item  ">
                <a class="nav-link text-light " href="{% url 'core:about' %}">About Us</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li>
            <li class="nav-item  ">
                <a class="nav-link text-light " href="{% url 'core:contact' %}">Contact Us</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li>
            {% comment %} <li class="nav-item  ">
                <a class="nav-link text-light " href="{% url 'core:gallery' %}">Gallery</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item  ">
                <a class="nav-link text-light " href="#">My Profile</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li> {% endcomment %}
            <li class="nav-item  ">
                <a class="nav-link text-light " href="{% url 'pos:products' %}">Orders</a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown2">
                </div>
            </li>
            <button id="install-button" style="display: none;">Install App</button>
        </ul>
    </div>
</nav>
<!-- ===============================end navbar============================== -->